// Remote exports the raw React component in Loader Mode.
// Types are declared here; in a real project they'd be generated by
// @module-federation/typescript or shipped as a published types package.
declare module 'catalog/entry' {
  import type { ComponentType } from 'react';

  export interface Product {
    id: string;
    name: string;
    price: number;
    category: string;
  }

  export interface ProductListProps {
    products: Product[];
    onAddToCart?: (product: { id: string; name: string; price: number }) => void;
  }

  export const ProductList: ComponentType<ProductListProps>;
}
